export enum RedisKeys {
    ALL_USERS = 'ALL_USERS',
    ALL_PRODUCTS = 'ALL_PRODUCTS',
    ALL_CATEGORIES = 'ALL_CATEGORIES',
    ALL_TRANSACTIONS = 'ALL_TRANSACTIONS',
    ALL_FILES = 'ALL_FILES',
    ALL_USER_ID = 'ALL_USER_ID_'
}